name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/PKGBUILD'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      pkgbuilds: ${{ steps.matrix.outputs.pkgbuilds }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0

      - name: Find updated packages and construct matrix
        id: matrix
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          dirs=$(git diff --name-only HEAD HEAD~1 "*/.SRCINFO" | xargs dirname)
          # Convert dirs that have been changes to a JSON array
          echo "pkgbuilds=$(printf '["%s"]' "$(echo "$dirs" | sed ':a;N;$!ba;s/\n/","/g')")" >> $GITHUB_OUTPUT

  publish:
    runs-on: ubuntu-latest
    needs: [ setup ]
    strategy:
      matrix:
        pkgbuild: ${{fromJSON(needs.setup.outputs.pkgbuilds)}}

    steps:
      - name: Publish packages
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.1 # v2.7.1
        if: ${{ matrix.pkgbuild != '' }}
        with:
          pkgname: packages/${{ matrix.pkgbuild }}
          pkgbuild: packages/${{ matrix.pkgbuild }}/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
