name: updpkgsums

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - '**/.SRCINFO'
      - '**/PKGBUILD'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      pkgbuilds: ${{ steps.matrix.outputs.pkgbuilds }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Find updated packages and construct matrix
        id: matrix
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          dirs=$(git diff --name-only HEAD HEAD~1 "*/.SRCINFO" | xargs dirname)
          # Convert dirs that have been changed to a JSON array
          echo "pkgbuilds=$(printf '["%s"]' "$(echo "$dirs" | sed ':a;N;$!ba;s/\n/","/g')")" >> $GITHUB_OUTPUT

  updpkgsums:
    runs-on: ubuntu-latest
    needs: [ setup ]
    strategy:
      matrix:
        pkgbuild: ${{fromJSON(needs.setup.outputs.pkgbuilds)}}

    steps:
      - name: Validate packages
        if: ${{ matrix.pkgbuild != '' }}
        uses: ./.github/actions/aur
        with:
          action: 'updpkgsums'
          pkgnames: ${{ matrix.pkgbuilds }}

      - name: Commit
        if: ${{ matrix.pkgbuild != '' }}
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          file_pattern: '*/PKGBUILD */.SRCINFO'
